### PR TITLE
ISSUE-72: datafy/nav extensibility for arbitrary Python objects

### PR DESCRIPTION
**Pull request by jjtolton**
Closes: https://github.com/cnuernber/libpython-clj/issues/72

e.g.
```clojure
(require '[libpython-clj.python :refer [py..]])
(require '[libpython-clj.require :refer [require-python pydafy]])
(require '[clojure.datafy :refer [datafy]])
(require-python 'requests)

(defmethod pydafy 'requests.models.Response [r]
  (py.. r -content (decode "latin-1")))

(-> "https://www.google.com" requests/get datafy) ;;=> <html>...
```

### CODE REVIEW

**Comment by jjtolton** [comment]
I'm not crazy about having to resort to strings for this dispatch but not sure how to do this dynamically otherwise!

**Comment by jjtolton** [comment]
@cnuernber let me know if there are other types I should include.  I got `PPyObject` and `PBridgeToJVM`, and that seems to work for most cases.

**Comment by jjtolton** [comment]
Also `pydafy` might be as stupid name for the multimethod.  Open to suggestions.

**Comment by cnuernber** [comment]
This looks good but I am concerned the nav support isn't perfect (which honestly isn't a blocker - one step at a time).

Have you tried this in the [rebel data viewer](http://rebl.cognitect.com/)?

It is a bit hypocritical for me to ask this since I didn't test the metadata pathway in Rebel....

Aside from the above, do you feel this PR is ready to land?  Maybe we can file another issue about Rebl and leave it there, thus landing this and moving a bit forward.

**Comment by jjtolton** [comment]
This may have been a lack of imagination on my part.  I'm not sure what is worth nav'ing in the standard library.  I'll look into it

**Comment by jjtolton** [comment]
Tested that datafy/nav seems to work with modules on REBL.  I'm not an expert on REBL so perhaps we can make a seperate issue for testing that.  Recommend closing on this and creating separate issue for REBL testing.

**Pull request merged**
