### PR TITLE
ISSUE-52 (specify python executable)

### PR DESCRIPTION
**Pull request by jjtolton**
Closes: https://github.com/cnuernber/libpython-clj/issues/52

Usage:

```clojure
(py/initialize! :python-executable "python3.7") ;; works
(py/initialize! :python-executable "path/to/virtual/env/python") ;; works
(py/initialize!) ;; works
```

### CODE REVIEW

**Comment by cnuernber** [comment]
This is a solid improvement.

Do we want the python executable to be specified via an environment variable like `PYTHON_EXECUTABLE`?

**Comment by cnuernber** [comment]
I merged the simplification and now there are conflicts with this PR, sorry!

**Comment by jjtolton** [comment]
No problem, I'll take care of it.  Regarding the env var, I think we should make that an option too, but local `:bind-ns` should override `PYTHON_EXECUTABLE`

**Comment by jjtolton** [comment]
I was also thinking a `python.edn` might be a good place to put that info.  Is it alright if we handle those in separate PRs?

**Pull request merged**
