### PR TITLE
added load-file function

### PR DESCRIPTION
**Pull request by behrica**
as discussed here: https://clojurians.zulipchat.com/#narrow/stream/215609-libpython-clj-dev/topic/embeded.20cli.20apps

### CODE REVIEW

**Comment by behrica** [comment]
I am not sure, about the use case of "not boot/up kill the vm".
Is it a "python developer", which wants to use Clojure (maybe due to one specific library)?

My use case is the equivalent of "clj hello.clj",

in which hello.clj contains some libpython-clj code.

Concretely I run it like thgis:

```bash
docker run  ..... ..... my-lib python3  -c "import sys;sys.path.append('/home/user');import cljbridge;cljbridge.load_clojure_file(clj_file='hello.clj)"
```

**Comment by behrica** [comment]
But indeed, I can see the "need" to "load" several clojure files, one after the other.

**Comment by behrica** [comment]
Maybe we should put this on hold.
I see know a more generalise requirement of configuring the "bootstrap"  of the JVM/Clojure process.
Example would be to start "a notespace server together with the nrepl":
I could look like this in python
```
    require("notespace.api")
    resolve_call_fn("notespace.api/init")
    resolve_call_fn("libpython-clj2.embedded/start-repl!",
                    py_dict_to_keyword_map(kw_args))

```
I am not sure, if this belongs here, or should that be done in Clojure side ?

My use case would be a Docker container, which start nrepl and notespace on startup

**Comment by behrica** [comment]
maybe teh "real need" is a cli tool, so a replacement for the "clj" launcher,
`clj-py`  which starts libpython clj on startup and then does the "right" think, supporting all options to execute clojure (as the `clj`) tool does.

Is this even feasable ?

**Comment by cnuernber** [comment]
I think it is feasible but this right now is a reasonable half step.

**Comment by behrica** [comment]
I think "both functions" is best compromise.
I can see three use cases:
1. start repl
2. run Clojure units tests, which require libpython-clj
3. run Clojure "clj" files for long running applications using libpython-clj
   -> i do that a lot,  as well in Docker

**Pull request merged**
